site_name: English

repo_url: https://github.com/rudict/english/

theme:
  name: material
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/theme-light-dark
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode
  features:
    - navigation.indexes

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Слова:
    - Существительные:
      - По категориям:
        - Люди: 
          - words/nouns/by_category/people/index.md
          - Тело человека: words/nouns/by_category/people/parts_of_the_body/100_the_human_body.md
          - Лицо: words/nouns/by_category/people/parts_of_the_body/101_face.md
