site_name: English
repo_url: https://github.com/rudict/english/

theme:
  name: material
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/theme-light-dark
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode
  features:
    - navigation.indexes

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Дорожная карта:
    - Для начинающих:
      - roadmap/beginner/index.md
      - Как рассказать о себе: roadmap/beginner/100_about_yourself.md
  - Грамматика:
    - Части речи:
      - Местоимения:
        - Местоимения: grammar/parts_of_speech/pronouns/100_pronouns.md
        - Указательные местоимения: grammar/parts_of_speech/pronouns/101_demonstrative_pronouns.md
    - Глаголы:
      - Глагол to be: grammar/verbs/100_to_be.md
