site_name: English

repo_url: https://github.com/rudict/english/

theme:
  name: material
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/theme-light-dark
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode
  features:
    - navigation.indexes

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Слова:
    - Существительные:
      - По категориям:
        - Люди: 
          - words/nouns/by_category/people/index.md
          - Тело человека: words/nouns/by_category/people/parts_of_the_body/100_the_human_body.md
          - Лицо: words/nouns/by_category/people/parts_of_the_body/101_face.md
      - A: words/nouns/a.md
      - B: words/nouns/b.md
      - C: words/nouns/c.md
      - D: words/nouns/d.md
      - E: words/nouns/e.md
      - F: words/nouns/f.md
      - G: words/nouns/g.md
      - L: words/nouns/l.md
      - R: words/nouns/r.md
      - V: words/nouns/v.md
      - W: words/nouns/w.md
      - Y: words/nouns/y.md
    - Глаголы:
      - По категориям:
        - Люди:
          - Тело: words/verbs/by_category/people/body.md
      - A: words/verbs/a.md
      - B: words/verbs/b.md
      - C: words/verbs/c.md
      - W: words/verbs/w.md
    - Прилагательные:
      - A: words/adjectives/a.md
      - B: words/adjectives/b.md
      - C: words/adjectives/c.md
      - D: words/adjectives/d.md
      - F: words/adjectives/f.md
      - H: words/adjectives/h.md
      - M: words/adjectives/m.md
      - R: words/adjectives/r.md
    - Наречия:
      - M: words/adverbs/m.md
  - Фразовые глаголы:
    - Belong: phrasal_verbs/belong.md
    - Check: phrasal_verbs/check.md
  - Идиомы:
    - H: idioms/h.md
